### ISSUE TITLE
Prometheus loses connection to Alertmanager after rescheduling of Alertmanager

### ISSUE THREAD

**Issue by pietervincken** [prometheus-operator/prometheus-operator#4913]
**What happened?**

Connection between Prometheus and Alertmanager is lost when Alertmanagers get rescheduled by the cluster.

**Did you expect to see something different?**

When pods are rescheduled (normal operation) Prometheus instances should be able to recover and connect to the correct alert manager instances again. 

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy a Prometheus through the operator
- Deploy an Alertmanager through the operator
- Reschedule the alertmanager pod (by deleting it manually, the pod IP should change for this bug to occur)
- Prometheus will now report that it cannot connect to the old instance and won't connect to the new pod of alertmanager (see logs)

**Environment**

* Prometheus Operator version:
`prometheus_operator_build_info{branch="refs/tags/v0.56.3",goversion="go1.17.10",revision="b3c140216b020547d368518b48fbf16448dcdd1b",version="0.56.3"}`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app-version: 2.15.2
    argocd.argoproj.io/tracking-id: cluster-configuration:apps/Deployment:operator-prometheus/prometheus-operator
    deployment.kubernetes.io/revision: "14"
  creationTimestamp: "2022-03-28T14:15:19Z"
  generation: 16
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: 0.56.3
  name: prometheus-operator
  namespace: operator-prometheus
  resourceVersion: "160987320"
  uid: 7fc05ac9-c7b0-4d7b-be24-3c218991f0c8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        app-version: 2.15.2
        kubectl.kubernetes.io/default-container: prometheus-operator
        kubectl.kubernetes.io/restartedAt: "2022-03-28T16:28:20+02:00"
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: 0.56.3
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=xxx/quay.io/prometheus-operator/prometheus-config-reloader:v0.56.3
        - --config-reloader-cpu-limit=200m
        image: xxx/quay.io/prometheus-operator/prometheus-operator:v0.56.3
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: 700m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: prometheus-operator
      serviceAccountName: prometheus-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-19T14:08:07Z"
    lastUpdateTime: "2022-05-19T14:08:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-28T14:28:20Z"
    lastUpdateTime: "2022-06-13T11:49:37Z"
    message: ReplicaSet "prometheus-operator-954c4b4b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

```

* Kubernetes version information:

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"5a97ee6d15525f6e4a1c2646bf1dfd2ebd5220b5", GitTreeState:"clean", BuildDate:"2022-06-15T04:26:33Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    Azure Kubernetes Service

* Manifests:

Prometheus
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    app-version: 2.75.0
    argocd.argoproj.io/tracking-id: cluster-configuration:monitoring.coreos.com/Prometheus:monitoring/k8s
  creationTimestamp: "2022-03-28T14:26:30Z"
  generation: 7
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.35.0
  name: k8s
  namespace: monitoring
  resourceVersion: "251695652"
  uid: 13a7d84b-943f-4e43-8e56-1f6f03a96fb1
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  enableFeatures: []
  evaluationInterval: 30s
  externalLabels:
    cluster: xxx
  image: xxx/quay.io/prometheus/prometheus:v2.35.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.35.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 2
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: sc-retained
  thanos:
    baseImage: xxx/quay.io/thanos/thanos
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objectstorage
    version: v0.26.0
  version: 2.35.0
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2022-07-13T00:04:30Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2022-07-12T22:36:05Z"
    status: "True"
    type: Reconciled
  paused: false
  replicas: 4
  shardStatuses:
  - availableReplicas: 2
    replicas: 2
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 2
  - availableReplicas: 2
    replicas: 2
    shardID: "1"
    unavailableReplicas: 0
    updatedReplicas: 2
  unavailableReplicas: 0
  updatedReplicas: 4
```

Alertmanager
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    app-version: 2.75.0
    argocd.argoproj.io/tracking-id: cluster-configuration:monitoring.coreos.com/Alertmanager:monitoring/main
  creationTimestamp: "2022-03-28T14:26:30Z"
  generation: 6
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.24.0
  name: main
  namespace: monitoring
  resourceVersion: "186860991"
  uid: 9861754e-7c33-437c-863d-3a5aa7deae7a
spec:
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: alertmanager
  image: xxx/quay.io/prometheus/alertmanager:v0.24.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.24.0
  replicas: 3
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.24.0
```

* Prometheus Operator Logs:

```
ts=2022-07-14T13:26:10.943Z caller=notifier.go:526 level=error component=notifier alertmanager=http://10.19.170.31:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://10.19.170.31:9093/api/v2/alerts\": context deadline exceeded"
ts=2022-07-14T13:26:20.944Z caller=notifier.go:526 level=error component=notifier alertmanager=http://10.19.170.31:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://10.19.170.31:9093/api/v2/alerts\": context deadline exceeded"
ts=2022-07-14T13:26:30.945Z caller=notifier.go:526 level=error component=notifier alertmanager=http://10.19.170.31:9093/api/v2/alerts count=2 msg="Error sending alert" err="Post \"http://10.19.170.31:9093/api/v2/alerts\": context deadline exceeded"
ts=2022-07-14T13:26:40.946Z caller=notifier.go:526 level=error component=notifier alertmanager=http://10.19.170.31:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://10.19.170.31:9093/api/v2/alerts\": context deadline exceeded"
```

**Anything else we need to know?**:

10.19.170.31 is the IP of one of the alert manager instance before it was rescheduled. After the reschedule, Prometheus keeps targetting that IP instead of performing a new lookup.

**Comment by slashpai** [comment]
alertmanager is identified automatically based on alertmanager endpoint details specified in `alerting` section of `Prometheus` object which translates to following relabel config in prometheus configuration if you used default kube-prometheus stack. So it based on alertmanager service name and  port specified. It may take sometime to get it reflected after new pod is created. 

```
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: alertmanager-main
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: web
      replacement: $1
      action: keep
```

Have you checked `kubectl get endpoints alertmanager-main` if that gets updated based on new alertmanager pod IP? Also does the error go away after sometime?

**Comment by pietervincken** [comment]
I updated to the latest version this morning and now I cannot reproduce it anymore, so it seems solved now. 

I looked at the service object as you suggested and that syncs almost instantly with pods coming up. After the upgrade that is also instantly reflected in the alertmanagers section of the Prometheus configuration UI. 

I'll close the issue.

**Comment by jurgenweber** [comment]
So this is happening to me right now, I am on 58.5.3 of the prom stack. Are tehre any other things to watch out for? Does it need to be on a headless service or is a standard service fine?

**Comment by alexanderwoehler** [comment]
Hi, as far as I can tell, the fix has not been backported into an LTS version yet. Are there any plans to do so?

**Comment by autarchprinceps** [comment]
Is this actually fixed? I am seeing no difference in behaviour on 68.5.0. It's still not reacting to changes in the Endpoint IPs for us.
