### ISSUE TITLE
Replace `gen-crd-api-reference-docs` for API documentation generation

### ISSUE THREAD

**Issue by ArthurSens** [prometheus-operator/prometheus-operator#6144]
In https://github.com/prometheus-operator/prometheus-operator/pull/6001 we noticed that inline structs in our API are not reflected by [gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs).

The author of gen-crd-api-reference-docs also mentions how the tool is not maintained anymore and other options, like [elastic/crd-ref-docs](https://github.com/elastic/crd-ref-docs), have already fixed the inline structs problem.

We want to move away from gen-crd-api-reference-docs for the reasons above

**Comment by slashpai** [comment]
I cleared my assignment as I didnt get enough time to work on this one but this can be a good one to get started for GSoc :)

**Comment by haanhvu** [comment]
> I cleared my assignment as I didnt get enough time to work on this one but this can be a good one to get started for GSoc :)

@slashpai maybe a good first issue tag so that folks can find?

**Comment by ArthurSens** [comment]
I haven't put the label before because I like [CNCF's guidelines for labeling something with good-first-issue](https://contribute.cncf.io/maintainers/templates/issue-labels/#good-first-issue), I'll try to improve the issue description later 😬

**Comment by slashpai** [comment]
@ArthurSens  sure, I think since replacing the gen library doesn't need to have prometheus-operator knowledge much it can be a tackle for someone familiar with go as well. Do you want to remove good first label on this?

**Comment by ArthurSens** [comment]
> @ArthurSens sure, I think since replacing the gen library doesn't need to have prometheus-operator knowledge much it can be a tackle for someone familiar with go as well. Do you want to remove good first label on this?

nah let's keep it :)

**Comment by mouad-eh** [comment]
just showing interest for working on this (already started in fact). I will follow up with a PR in the upcoming days.

**Comment by mouad-eh** [comment]
I have been experimenting with [elastic/crd-ref-docs](https://github.com/elastic/crd-ref-docs) today and here are some important notes I took:
- If we want to migrate to this tool, we cannot just change the binary and expect everthing to work seamlessly because this fork is a lot different from the original repo. Both config file and templates needs to be changed as they have different fields and structure.
- It is true that this fork support type embedding but It didn't work when I tried it with prometheus-operator api files. the reason is that pointers are used for the type embedding (in the case of ProxyConfig) and they do not support that, they only support struct types embedding.
- ` // +kubebuilder:object:root=true` need to be added as a comment to highlight resource types from other types.
- When I tried the default templates provided on their repo , I found that resource types are not listed first before other types and they rely strictly on the alphabetical order for sorting.

@slashpai @ArthurSens your thoughts on this?

**Comment by ArthurSens** [comment]
Thanks for taking a look!

> * If we want to migrate to this tool, we cannot just change the binary and expect everthing to work seamlessly because this fork is a lot different from the original repo. Both config file and templates needs to be changed as they have different fields and structure.

Yeah, that was expected I guess... no problems in changing everything, it's just a lot of work 😬 

> * It is true that this fork support type embedding but It didn't work when I tried it with prometheus-operator api files. the reason is that pointers are used for the type embedding (in the case of ProxyConfig) and they do not support that, they only support struct types embedding.

Oh damn, that's a boomer. I'm not sure what would be the impact if we change this, maybe that's fine to change?

> * ` // +kubebuilder:object:root=true` need to be added as a comment to highlight resource types from other types.
> * When I tried the default templates provided on their repo , I found that resource types are not listed first before other types and they rely strictly on the alphabetical order for sorting.

That's an easy fix :) no problems adding that annotation and no problems sorting things alphabetically

**Comment by haanhvu** [comment]
#6400 has been fixed. Seems like that has fixed this issue too?

**Comment by mouad-eh** [comment]
Yes definitely. I thought the two issues were closed. However, if embedded struct pointers are used again the issue may reappear. That's why it is still open I guess.

**Comment by ArthurSens** [comment]
The tool we're using is still deprecated, in my opinion we still want to replace it 😬

**Comment by Clemo97** [comment]
@ArthurSens so I was following the thread and it seems to me that this issue was partially solved?

**Comment by ArthurSens** [comment]
Yes, we're still looking for a replacement. Ideally this new tool creates separate Markdown files for each CRD, or at least with some additional scripting :)

This aligns with @AshwinSriram11 proposal for the website revamp

**Comment by AshwinSriram11** [comment]
Will try to add more information after further testing. 👍

**Comment by AshwinSriram11** [comment]
After testing `elastic-ref-docs`, here are some more pointers:

-  The external links to Kubernetes docs are working after changing the version in the config file.
-  The description of some fields fits on the screen, while for some fields it is overflowing. My guess is that using fields inside a struct that are already a struct in themselves, or using **custom types**, causes the content to overflow out of the screen, which is not the case with a struct having normal data fields.
- Inline structs are not reflected in `elastic-ref-docs` just like `gen-crd-api-ref-docs`. Need to verify this after further testing.
- I can split the API reference page into 3 pages, v1, v1alpha1, and v1beta1,i.e, one page per package for separation of concerns.

So, the scrolling problem is not 100% solved, but it is a better option. One approach would be to replace `gen-crd-api-ref-docs` with `elastic-ref-docs` and then try to remove the right side navbar for these reference files, giving more width to view the description of various fields. But regarding the main issue of inline structs not being visible, we still need to check whether this fulfills the role.
